### ISSUE TITLE
KeyError: 'id'

### ISSUE THREAD

**Issue by driz** [aktavor69/pthbetter#13]
Python 2.7.3
installed requirements using pip and the requirements.txt; followed the README.md specifically.

`Logging in to passtheheadphones ...
Searching for transcode candidates...
You supplied one or more release URLs, ignoring your configuration's media types.
Traceback (most recent call last):
  File "/usr/local/bin/pthbetter", line 4, in <module>
    __import__('pkg_resources').run_script('pthbetter==1.7', 'pthbetter')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 739, in run_script

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1501, in run_script

  File "/usr/local/lib/python2.7/dist-packages/pthbetter-1.7-py2.7.egg/EGG-INFO/scripts/pthbetter", line 221, in <module>

  File "/usr/local/lib/python2.7/dist-packages/pthbetter-1.7-py2.7.egg/EGG-INFO/scripts/pthbetter", line 123, in main

KeyError: 'id'
`

**Comment by driz** [comment]
this is user error. When right click copying the permlink to a flac, it doesn't contain the ID. clicking the PL and copying the url contains the proper ID. Sorry for the inconvenience.
