### ISSUE TITLE
special characters in password break parsing

### ISSUE THREAD

**Issue by glarue** [aktavor69/pthbetter#14]
Certain special characters in the `password` field of `config` seem to be interpreted as Python code:

> Traceback (most recent call last):
>   File "/usr/local/bin/pthbetter", line 4, in <module>
>     __import__('pkg_resources').run_script('pthbetter==1.7', 'pthbetter')
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/local/lib/python2.7/dist-packages/pthbetter-1.7-py2.7.egg/EGG-INFO/scripts/pthbetter", line 221, in <module>
>     
>   File "/usr/local/lib/python2.7/dist-packages/pthbetter-1.7-py2.7.egg/EGG-INFO/scripts/pthbetter", line 84, in main
>     
>   File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
>     return self._interpolate(section, option, value, d)
>   File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
>     self._interpolate_some(option, L, rawval, section, vars, 1)
>   File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
>     "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
> ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%PGQIco#z'"

This should be solvable by reading the entry as a raw string or somesuch.

**Comment by noah552** [comment]
i think [RawConfigParser()](https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser) might fix the problem with '%' at least.

btw, that's not your password on the last line of the traceback is it?

**Comment by glarue** [comment]
> btw, that's not your password on the last line of the traceback is it?

Thanks for checking - it _was_ (only part of it), but I changed my password before posting it here.

**Comment by maki-chan** [comment]
That's a problem with the config parser indeed. If you have a `%` sign in your password, you need to insert it twice. For example, if my password was `No%Password` you would need to have this line in your config file:

    password = No%%Password
