### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Codgedodger** [aktavor69/pthbetter#17]
`Release found: A'Arab Zaraq Lucid Dreaming (1997)
Release URL: https://passtheheadphones.me/torrents.php?id=181219&torrentid=329737#torrent329737
Traceback (most recent call last):
  File "./pthbetter", line 221, in <module>
    main()
  File "./pthbetter", line 150, in main
    flac_dir = flac_dir.encode(sys.getfilesystemencoding())
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position 54: ordinal not in range(256)
`

**Comment by guywithabeard** [comment]
Seconded, unicode characters aren't being properly parsed it seems:

```Release found: La Femme sans Tête (2002)
Release URL: xxxxxx
Traceback (most recent call last):
  File "/usr/local/bin/pthbetter", line 4, in <module>
    __import__('pkg_resources').run_script('pthbetter==1.7', 'pthbetter')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pthbetter-1.7-py2.7.egg/EGG-INFO/scripts/pthbetter", line 221, in <module>

  File "/usr/local/lib/python2.7/dist-packages/pthbetter-1.7-py2.7.egg/EGG-INFO/scripts/pthbetter", line 150, in main

UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 52: ordinal not in range(128)```
